import { 
  Home, 
  Users, 
  Clock, 
  Calendar, 
  FileText, 
  Settings, 
  LogOut, 
  Plus, 
  Search, 
  Download, 
  Upload, 
  Database, 
  Info, 
  Trash, 
  Edit, 
  ChevronDown, 
  Mail, 
  AlertCircle,
  MapPin,
  TrendingUp,
  Package,
  UserPlus,
  BarChart3,
  DollarSign,
  Briefcase,
  LayoutDashboard,
  Video,
  PlaySquare,
  Megaphone,
  CheckCircle2,
  XCircle,
  Clock3,
  History
} from 'lucide-react';

export const Icons = {
  Home,
  Users,
  Clock,
  Calendar,
  FileText,
  Settings,
  LogOut,
  Plus,
  Search,
  Download,
  Upload,
  Database,
  Info,
  Trash,
  Edit,
  ChevronDown,
  Mail,
  AlertCircle,
  MapPin,
  TrendingUp,
  Package,
  UserPlus,
  BarChart3,
  DollarSign,
  Briefcase,
  LayoutDashboard,
  Video,
  PlaySquare,
  Megaphone,
  CheckCircle2,
  XCircle,
  Clock3,
  History
};

export const BANK_OPTIONS = [
  'BCA',
  'MANDIRI',
  'BNI',
  'BRI',
  'BSI',
  'CIMB NIAGA',
  'DANAMON',
  'PERMATA',
  'OCBC NISP',
  'PANIN',
  'BTN',
  'DANA',
  'OVO',
  'GOPAY',
  'SHOPEEPAY'
];

export const DEFAULT_SHIFTS = [
  { id: 'S1', name: 'Pagi', startTime: '08:00', endTime: '17:00', color: '#3b82f6' },
  { id: 'S2', name: 'Siang', startTime: '12:00', endTime: '21:00', color: '#f59e0b' },
  { id: 'S3', name: 'Malam', startTime: '21:00', endTime: '06:00', color: '#6366f1' },
  { id: 'OFF', name: 'Libur', startTime: '00:00', endTime: '00:00', color: '#ef4444' }
];
